- name: Import the repository key
  apt_key: id=5E6DA83306132997 keyserver='keyserver.ubuntu.com' state={{ packages_state }}

- name: Create the repo source file
  apt_repository: repo='deb http://zeroc.com/download/apt/ubuntu{{ ansible_distribution_version }} stable main' \
                  state={{ packages_state }} \
                  filename='ice'
  when:
    - ansible_distribution == 'Ubuntu'

- name: Create the repo source file
  apt_repository: repo='deb http://zeroc.com/download/apt/debian{{ ansible_distribution_major_version }} stable main' \
                  state={{ packages_state }} \
                  filename='ice'
  when:
    - ansible_distribution == 'Debian'
